import type { Task } from "./types/task";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Set up project repository",
    description: "Initialize Git repository and set up GitHub with proper branch protection rules",
    status: "done",
    assigneeId: "user1",
    assigneeName: "Alice Johnson",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    createdById: "user1",
    createdByName: "Alice Johnson",
  },
  {
    id: "2",
    title: "Design database schema",
    description: "Create ERD and define tables for users, tasks, and related entities",
    status: "done",
    assigneeId: "user2",
    assigneeName: "Bob Smith",
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-17"),
    createdById: "user2",
    createdByName: "Bob Smith",
  },
  {
    id: "3",
    title: "Implement authentication",
    description: "Set up Clerk authentication with proper role-based access control",
    status: "in-progress",
    assigneeId: "user1",
    assigneeName: "Alice Johnson",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-20"),
    createdById: "user3",
    createdByName: "Charlie Brown",
  },
  {
    id: "4",
    title: "Create API endpoints",
    description: "Build RESTful API endpoints for CRUD operations on tasks",
    status: "in-progress",
    assigneeId: "user2",
    assigneeName: "Bob Smith",
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
    createdById: "user1",
    createdByName: "Alice Johnson",
  },
  {
    id: "5",
    title: "Build task board UI",
    description: "Create kanban board interface with drag-and-drop functionality",
    status: "in-progress",
    assigneeId: "user3",
    assigneeName: "Charlie Brown",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-21"),
    createdById: "user2",
    createdByName: "Bob Smith",
  },
  {
    id: "6",
    title: "Add real-time updates",
    description: "Implement WebSocket connections for live task updates",
    status: "backlog",
    assigneeId: undefined,
    assigneeName: undefined,
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
    createdById: "user1",
    createdByName: "Alice Johnson",
  },
  {
    id: "7",
    title: "Write unit tests",
    description: "Create comprehensive test suite for all components and API endpoints",
    status: "backlog",
    assigneeId: "user2",
    assigneeName: "Bob Smith",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
    createdById: "user3",
    createdByName: "Charlie Brown",
  },
  {
    id: "8",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing and deployment",
    status: "backlog",
    assigneeId: undefined,
    assigneeName: undefined,
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
    createdById: "user1",
    createdByName: "Alice Johnson",
  },
  {
    id: "9",
    title: "Create user documentation",
    description: "Write comprehensive user guide and API documentation",
    status: "backlog",
    assigneeId: "user3",
    assigneeName: "Charlie Brown",
    createdAt: new Date("2024-01-23"),
    updatedAt: new Date("2024-01-23"),
    createdById: "user2",
    createdByName: "Bob Smith",
  },
];

export function getMockTasksByColumn() {
  return {
    backlog: mockTasks.filter(task => task.status === "backlog"),
    "in-progress": mockTasks.filter(task => task.status === "in-progress"),
    done: mockTasks.filter(task => task.status === "done"),
  };
} 