/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AppVpc": {
      "type": "sst.aws.Vpc"
    }
    "AuthFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "AuthStorage": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SharedDevDatabase": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "web": {
      "type": "sst.aws.React"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}